services:
  qr-generator:
    build:
      context: .
      dockerfile: Dockerfile
      driver: docker
    image: shah1011/qreator:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    container_name: qreator

  # Development service (optional)
  # qr-generator-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "3001:3000"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #     - /app/.next
  #   environment:
  #     - NODE_ENV=development
  #   restart: unless-stopped
  #   container_name: qr-generator-dev
  #   profiles:
  #     - dev
